name: Sync Files from Main Repo to New Repo

on:
  push:
    branches:
      - main

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository (New Repo)
    - name: Checkout New Repo
      uses: actions/checkout@v3
      with:
        repository: MokshaDill/Rock-Paper--Scissors-Lizard-Spock-api  # Replace with the new repo's name if needed

    # Checkout the Main Repo (Private Repo) using Personal Access Token (PAT)
    - name: Checkout Main Repo
      uses: actions/checkout@v3
      with:
        repository: MokshaDill/Rock-Paper--Scissors-Lizard-Spock  # Replace with the correct main repo name
        token: ${{ secrets.GH_TOKEN }}  # Replace this with your secret token
        ref: master  # Make sure the branch name is correct (use "main" if that's the branch name)

    # Sync specific files from the main repo to the new repo
    - name: Sync Files from Main Repo to New Repo
      run: |
        echo "Syncing the specific files..."
        # Make sure the target directories exist before syncing
        mkdir -p /home/runner/work/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock-api/artifacts/models
        rsync -avz --progress /home/runner/work/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock/artifacts/models/model.h5 Rock-Paper--Scissors-Lizard-Spock-api/artifacts/models/
        rsync -avz --progress /home/runner/work/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock/main.py Rock-Paper--Scissors-Lizard-Spock-api/
        rsync -avz --progress /home/runner/work/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock/requirements.txt Rock-Paper--Scissors-Lizard-Spock-api/

    # Commit and push the changes to the new repo
    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Sync specific files from the main repo"
        git push
