name: Sync Specific Files from Main Repo

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the 'main' branch of the new repo
  schedule:
    - cron: '0 * * * *'  # Runs every hour, adjust as necessary

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repo (Private)
        uses: actions/checkout@v3
        with:
          repository: MokshaDill/Rock-Paper--Scissors-Lizard-Spock  # Main repo (private)
          ref: master  # Checkout from 'master' branch of the main repo
          token: ${{ secrets.MAIN_REPO_TOKEN }}  # Use the PAT secret for authentication

      - name: List contents of the main repo directory (Debugging)
        run: |
          echo "Listing contents of the main repo directory:"
          ls -R ${{ github.workspace }}  # Check the root and subdirectories

      - name: List contents of the artifacts directory (Debugging)
        run: |
          echo "Listing contents of the artifacts directory:"
          ls -R ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock/artifacts/  # Check specifically inside 'artifacts/'

      - name: Create target directories if they don't exist
        run: |
          mkdir -p ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock-api/artifacts/models
          mkdir -p ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock-api

      - name: Copy Specific Files from Main Repo to New Repo
        run: |
          # Check and sync files if the directories exist
          if [ -d "${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock/artifacts/models" ]; then
            rsync -avz --progress ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock/artifacts/models/model.h5 ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock-api/artifacts/models/
          else
            echo "Directory 'models' not found in main repo"
          fi

          if [ -f "${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock/main.py" ]; then
            rsync -avz --progress ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock/main.py ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock-api/
          else
            echo "main.py not found in the main repo"
          fi

          if [ -f "${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock/requirements.txt" ]; then
            rsync -avz --progress ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock/requirements.txt ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock-api/
          else
            echo "requirements.txt not found in the main repo"
          fi

      - name: Commit and Push Changes to New Repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Synced specific files from main repo" || echo "No changes to commit"
          git push
