name: Sync Specific Files from Main Repo

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the 'main' branch of the new repo
  schedule:
    - cron: '0 * * * *'  # Runs every hour, adjust as necessary

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repo (Private)
        uses: actions/checkout@v3
        with:
          repository: MokshaDill/Rock-Paper--Scissors-Lizard-Spock  # Main repo (private)
          ref: master  # Checkout from 'master' branch of the main repo
          token: ${{ secrets.MAIN_REPO_TOKEN }}  # Use the PAT secret for authentication

      - name: List contents of the current directory (Debugging)
        run: |
          ls -R

      - name: List contents of the main repo directory
        run: |
          ls -R ${{ github.workspace }}

      - name: Create target directories if they don't exist
        run: |
          mkdir -p Rock-Paper--Scissors-Lizard-Spock-api/artifacts/models
          mkdir -p Rock-Paper--Scissors-Lizard-Spock-api

      - name: Copy Specific Files from Main Repo to New Repo
        run: |
          # Sync the specific files from the main repo to the new repo
          rsync -avz --progress ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock/artifacts/models/model.h5 Rock-Paper--Scissors-Lizard-Spock-api/artifacts/models/
          rsync -avz --progress ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock/main.py Rock-Paper--Scissors-Lizard-Spock-api/
          rsync -avz --progress ${{ github.workspace }}/Rock-Paper--Scissors-Lizard-Spock/requirements.txt Rock-Paper--Scissors-Lizard-Spock-api/

      - name: Commit and Push Changes to New Repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Synced specific files from main repo" || echo "No changes to commit"
          git push
