name: Sync Files from Main Repo to New Repo

on:
  push:
    branches:
      - main

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository (New Repo)
    - name: Checkout New Repo
      uses: actions/checkout@v3
      with:
        repository: MokshaDill/Rock-Paper--Scissors-Lizard-Spock-api
        token: ${{ secrets.MAIN_REPO_TOKEN}}  # Use the fine-grained token

    # Checkout the Main Repo (Private Repo)
    - name: Checkout Main Repo
      uses: actions/checkout@v3
      with:
        repository: MokshaDill/Rock-Paper--Scissors-Lizard-Spock
        token: ${{ secrets.GH_TOKEN }}  # Reference the fine-grained token
        ref: master  # Adjust the branch name if needed

    # Create the 'models' directory if it doesn't exist
    - name: Create models directory
      run: |
        mkdir -p /home/runner/work/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock/artifacts/models

    # Sync specific files from the main repo to the new repo
    - name: Sync Files from Main Repo to New Repo
      run: |
        rsync -avz --progress /home/runner/work/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock/artifacts/models/model.h5 /home/runner/work/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock-api/artifacts/models/
        rsync -avz --progress /home/runner/work/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock/main.py /home/runner/work/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock-api/
        rsync -avz --progress /home/runner/work/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock/requirements.txt /home/runner/work/Rock-Paper--Scissors-Lizard-Spock-api/Rock-Paper--Scissors-Lizard-Spock-api/

    # Commit and push the changes to the new repo
    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Sync specific files from the main repo"
        git push
